FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY pbx_portal ./pbx_portal
COPY scripts ./scripts

EXPOSE 5000

CMD ["gunicorn", "app:app"]
